Create Wumpus Stub
thewumper/Wumpus pull request #13
Opened 2024-02-08 19:04 UTC by ILHS2000503

2024-02-08 19:06 UTC, MaximumMaxxx submitted a review, later dismissed
Can we switch state into an enum instead of an int

2024-02-08 19:08 UTC, ILHS2000503 commented
dont know what an enum is

2024-02-09 19:15 UTC, roguefirework requested changes
Can you quickly remove the unnesary imports

2024-02-09 19:15 UTC, roguefirework commented on Core/WumpusCore/Wumpus/Wumpus.cs
> +using System.Linq;
Unneeded Import

2024-02-09 19:15 UTC, roguefirework commented on Core/WumpusCore/Wumpus/Wumpus.cs
> +using System.Security.Cryptography.X509Certificates;
Uneeded

2024-02-09 19:15 UTC, roguefirework commented on Core/WumpusCore/Wumpus/Wumpus.cs
> +using System.Text;
I think we dont need this

2024-02-09 19:15 UTC, roguefirework commented on Core/WumpusCore/Wumpus/Wumpus.cs
> +using System.Threading.Tasks;
Dont see any threading code atm

2024-02-09 19:33 UTC, roguefirework approved these changes
Looks good now

2024-02-09 19:39 UTC, ilhs1041495 approved these changes

2024-02-09 19:40 UTC, 1118422ILHS requested changes
Doc should be typed better

2024-02-12 19:09 UTC, ILHS2000503 commented
what doc?

2024-02-12 19:24 UTC, ILHS2000503 commented
Changed the docs to be a bit more detailed and specify that more detailed summaries will be added latter.

2024-02-12 19:28 UTC, 1118422ILHS approved these changes
Comments are better. "Better description coming soon" unnecessary but fine. Remember to use parameter and returns tags once necessary.

2024-02-12 19:29 UTC, merged