Fix issues with the Main branch
thewumper/Wumpus pull request #21
Opened 2024-02-09 19:44 UTC by ilhs1096069

* Replaced the old testing with a project (.net 7.0) with one that's on the right version (.net framework 4.8)
* Removed `StoredHighScore` from being in the files to compile as it does not exist anymore

:)

2024-02-09 19:48 UTC, roguefirework requested changes

2024-02-09 19:48 UTC, roguefirework commented on Core/WumpusTesting/UnitTest1.cs
Maybe delete this?

2024-02-09 19:51 UTC, ilhs1096069 commented on Core/WumpusTesting/UnitTest1.cs
fixed

2024-02-12 19:04 UTC, 1118422ILHS approved these changes
Please don't make silly mistakes like this again

2024-02-12 19:05 UTC, roguefirework approved these changes
It may in fact look good to someone whos name may be me

2024-02-12 19:05 UTC, roguefirework commented on Core/WumpusTesting/Properties/AssemblyInfo.cs
> +[assembly: AssemblyCompany("Northshore School District No.417")]
Real

2024-02-12 19:06 UTC, merged