Add map editor
thewumper/Wumpus pull request #45
Opened 2024-03-11 18:46 UTC by roguefirework

Pretty much non of this code scales well but it is a quick map editor that kinda works

2024-03-11 18:49 UTC, ilhs1096069 requested changes
Remove random ugly spaces and I'll approve :)

2024-03-13 19:37 UTC, MaximumMaxxx requested changes

2024-03-13 19:37 UTC, MaximumMaxxx commented on Core/Map Editor/Program.cs
Why don't you make a constructor for topology that just accepts a string instead of writing to the disk and reading from it

2024-03-18 18:06 UTC, ilhs1096069 approved these changes
LGTM

2024-03-18 18:08 UTC, MaximumMaxxx approved these changes
Yipeee

2024-03-18 18:08 UTC, merged