Please don't merge yet
thewumper/Wumpus pull request #49
Opened 2024-03-19 16:39 UTC by roguefirework

See title

2024-03-21 16:50 UTC, MaximumMaxxx requested changes
Typo in docs, please fix

2024-04-18 17:17 UTC, MaximumMaxxx approved these changes
I agree

2024-04-18 17:24 UTC, 1118422ILHS requested changes
Test it.

2024-04-18 17:24 UTC, 1118422ILHS commented on Core/WumpusCore/GameLocations/GameLocations.cs
> +            if (numVats + numRats + numAcrobats + numBats >= 30)
Replace 30 with topology.numRooms

2024-04-18 17:29 UTC, 1118422ILHS requested changes
No more ushorts

2024-04-22 18:10 UTC, 1118422ILHS commented on Core/WumpusTesting/ControllerTest.cs
>          public void testMap()
whurg?

2024-04-22 18:12 UTC, ilhs1096069 requested changes
Please add docs to the file I said to

2024-04-22 18:12 UTC, ilhs1096069 commented on Core/WumpusCore/Topology/Graph.cs
Please add some docs to this file :(

2024-04-22 18:12 UTC, 1118422ILHS approved these changes
Appears exquisite to the eyes.

2024-04-22 18:25 UTC, ilhs1096069 approved these changes
Yippee it looks good now thank you

2024-04-22 18:29 UTC, merged