Merge current state of UI insto main
thewumper/Wumpus pull request #60
Opened 2024-04-19 18:41 UTC by MaximumMaxxx

This is the beginning of as somewhat functional UI. We now having moving between rooms, a basic wumpus implementation and a whole lot more.

This PR also includes the console UI project, although seeing as Silas has left that might be deprecated in the future.

2024-04-19 18:46 UTC, 1118422ILHS requested changes
I cannot allow the duplication of files. It needs to be easy to make changes to a file and this is stupid also

2024-04-22 18:16 UTC, 1118422ILHS requested changes
misspelling

2024-04-22 18:17 UTC, ilhs1096069 approved these changes
This will help :)

2024-04-22 18:18 UTC, havecookies commented on Core/WumpusCore/Controller/Controller.cs
> +        public Controller(string trviaFile, string topologyDirectory, ushort mapId)
fixed

2024-04-25 18:03 UTC, merged