Finished Wumpus
thewumper/Wumpus pull request #63
Opened 2024-05-03 18:25 UTC by 1118422ILHS

2024-05-13 18:29 UTC, roguefirework requested changes

2024-05-13 18:29 UTC, roguefirework commented on Core/WumpusCore/Wumpus/Wumpus.cs
> +        public void setState(int newState)
This can take a state maybe?

2024-05-13 18:29 UTC, roguefirework commented on Core/WumpusCore/Wumpus/Wumpus.cs
> +        public int getWumpState()
This can return a state not an int

2024-05-16 17:08 UTC, roguefirework approved these changes
Looks good

2024-05-16 18:08 UTC, MaximumMaxxx approved these changes
I agree

2024-05-17 18:33 UTC, merged